### ISSUE TITLE
Help with vendor location.

### ISSUE THREAD

**Issue by alnutile** [consolidation/cgr#20]
Just wondering if I am just missing a well known setting or not. My package has a file in the root that references

```
#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap/autoload.php';
```
and then in that file

```
require __DIR__.'/../vendor/autoload.php';
```

And works fine as I am working on it but if I try to install it on a system it ends up not being able to access this location unless I type 

```
cd vendor/foo/bar/ && ln -s ../../../vendor .
```

Then it works.

What is the best way to code my main file so it works fine before and after installation?

Thanks

**Comment by greg-1-anderson** [comment]
Your package is designed to be used as the root package (e.g. installed via `git clone` + `composer install`, or via `composer create-project`), and is not set up to work when installed as the dependency of some other project. The later mode is what happens when you install via `composer global require` or, equivalently, via cgr.

In order to work in both configurations, an application must look for its autoload file in multiple locations. See the example [robo](https://github.com/consolidation/Robo/blob/master/robo#L11) script from the Robo PHP project for one example of this. Phar support is, of course, optional.

**Comment by alnutile** [comment]
thanks for the tip.
Why btw does Robo use phar? Seems phar would not be needed in these cases? Just curious.

Thanks

**Comment by greg-1-anderson** [comment]
Phars are popular among some users, because it is simple to download and run. However, a phar complicates other things, such as dynamic application composition (e.g. plugins) via composer. Therefore, some applications are moving away from phar support. Some choose to still support it, though.

**Comment by alnutile** [comment]
thanks again.
