### ISSUE TITLE
Installation unclear

### ISSUE THREAD

**Issue by maniac0s** [consolidation/cgr#29]
I have tried to install cgr but the process the readme describes doesn't work.

My composer is in /usr/local/bin
I run 

    ~/cgr# composer global require consolidation/cgr 
    Changed current directory to /root/.config/composer
    Do not run Composer as root/super user! See https://getcomposer.org/root for details
    Using version ^2.0 for consolidation/cgr
    ./composer.json has been created
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 1 install, 0 updates, 0 removals
      - Installing consolidation/cgr (2.0.4): Downloading (100%)         
    Writing lock file
    Generating autoload files

    ~/cgr# export PATH="$HOME/.composer/vendor/bin:$PATH"

    ~# cgr
    -bash: cgr: command not found

~/.composer does not exist. Why is this and how do I fix that? Creating ~/.composer doesn't help either

**Comment by greg-1-anderson** [comment]
Some systems install to `$HOME/.config/composer` instead of `$HOME/.composer`. Adjust your $PATH appropriately.

Also, it would be best to install and use Composer as some non-root user. Any package that you install can run code at install time.

**Comment by maniac0s** [comment]
Thanks. On debian it seems to be .config (why ever, for me it doesn't make sense at all to have it under a folder .config which could be basically anything). Is it possible to reflect that in the documentation or is there a way to find out what folder my installation uses in general?

**Comment by greg-1-anderson** [comment]
@maniac0s I updated the README to be more general vis-a-vis platform variations that may exist.

**Comment by therobyouknow** [comment]
**I needed to symlink from `/usr/local/bin`**

@maniac0s @greg-1-anderson 

In order to run cgr but just typing `cgr` (and therefore eliminating the `bash: cgr: command not found` error), I had to symlink cgr from `/usr/local/bin` using the following command:

`sudo ln -s ~/.config/composer/vendor/bin/cgr .`

then I could use cgr to run cgr, and go on to use it to install drush

`cgr drush/drush`

(as prescribed by: https://github.com/consolidation/cgr#installation-and-usage )

Likewise, I have to also symlink drush from `/usr/local/bin` to be able to just use drush at the command line to run drush

`sudo ln -s ~/.config/composer/vendor/bin/drush .`

Be careful to use -s (i.e. lower case s, not upper case S) as the option/switch as upper-case means something completely different - "hard link" (and you'll get the error: `ln: .: hard link not allowed for directory` if you try to use capital/uppercase S)

**My environment:** 

Ubuntu 16.04.4 LTS 64bit on DigitalOcean
I used a non-root user to install composer, then cgr and drush - my user is called `web` and belongs to the following groups: `web sudo www-data lxd docker`

**Other references:**
https://askubuntu.com/questions/866161/setting-path-variable-in-etc-environment-vs-profile
https://getcomposer.org/doc/00-intro.md#globally
https://getcomposer.org/download/

**What didn't work (to stop the `command not found error` - and therefore actually be able to run cgr):**

Setting the $PATH variable (and permanently at that in /etc/environment) to point to the $HOME/.config/composer/vendor/bin folder to look for the command there, did not work - I got that same command not found error.

The contents of my `/etc/environment` file are as follows:

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:$HOME/.config/composer:$HOME/.config/composer/vendor/bin"

(I ran the command `source /etc/environment` so that the additions to the $PATH variable to add that vendor/bin path were picked up, saving logging out and back in)
