### ISSUE TITLE
Doesn't pick up upgrade

### ISSUE THREAD

**Issue by amenk** [consolidation/cgr#35]
amk@orange:~/.composer/global/mage2tv/magento-cache-clean$ cat composer.json 
	{
	    "require": {
		"mage2tv/magento-cache-clean": "^0.0.33"
	    }
	}

	amk@orange:~/.composer/global/mage2tv/magento-cache-clean$ composer show mage2tv/magento-cache-clean
	name     : mage2tv/magento-cache-clean
	descrip. : A faster drop in replacement for bin/magento cache:clean with file watcher
	keywords : development, magento, utility
	versions : * 0.0.33
	type     : library
	license  : BSD 3-Clause "New" or "Revised" License (BSD-3-Clause) (OSI approved) https://spdx.org/licenses/BSD-3-Clause.html#licenseText
	source   : [git] https://github.com/mage2tv/magento-cache-clean.git 45bac59796c47ee9f85d9be2d0dcb7c636487b46
	dist     : [zip] https://api.github.com/repos/mage2tv/magento-cache-clean/zipball/45bac59796c47ee9f85d9be2d0dcb7c636487b46 45bac59796c47ee9f85d9be2d0dcb7c636487b46
	path     : /home/amk/.composer/global/mage2tv/magento-cache-clean/vendor/mage2tv/magento-cache-clean
	names    : mage2tv/magento-cache-clean

	suggests

	amk@orange:~/.composer/global/mage2tv/magento-cache-clean$ composer update
	Loading composer repositories with package information
	Updating dependencies (including require-dev)
	Nothing to install or update
	Generating autoload files

	amk@orange:~/.composer/global/mage2tv/magento-cache-clean$ composer why-not mage2tv/magento-cache-clean 0.0.35
	__root__  -  requires  mage2tv/magento-cache-clean (^0.0.33)  

Why does it not update?

**Comment by Vinai** [comment]
I needed to `rm -r ~/.composer/cache/files/mage2tv/magento-cache-clean` for composer to see the new release directly after pushing it.

**Comment by amenk** [comment]
Already did a `composer clear-cache`

**Comment by greg-1-anderson** [comment]
If the tag is very new, you can look on packagist.org and see if it's there yet.

Sometimes Composer becomes confused and can't manage updates due to issues between the dependencies in composer.lock vs the dependencies in the newer version. You can sometimes get around this by dumping composer.lock and vendor and trying again. Put ^0.0.35 in your composer.json for a really big hammer. Note that this usually isn't an issue for projects with only one primary dependency.

Finally, if the newer version of the package you are trying to update has added a more restrictive php version that no longer matches what is installed, or has added a php extension that used to not be a requirement, and is not installed on your system, sometimes Composer fails to report that constraint. You might see a better message if you remove vendor / composer.lock as described above.

Not a cgr issue, so closing.

**Comment by amenk** [comment]
Composer is strange :-) Thanks for your elaborate feedback, and I am okay with closing..

but

* in composer show it's showing

It's very strange.
Still it's not working without putting 0.0.35 in the composer.json -- and I was expecting cgr to just upgrade everything when I do `cgr update`

**Comment by greg-1-anderson** [comment]
Yeah, that's up to Composer. I couldn't tell you why it got stuck there.
