### ISSUE TITLE
Purpose of this tool / Why not tell people they can use regular require/require-dev instead?

### ISSUE THREAD

**Issue by naderman** [consolidation/cgr#36]
Can you help me understand what the purpose of this tool is? As far as I can see you really just end up installing per-project dependencies into a non-standard directory. If one doesn't want to share these tools across projects, why wouldn't one just use a regular require/require-dev in the project itself and avoid all of this?

May it make sense to modify the README to recommend people use require/require-dev instead of this tool if they have project specific dependencies?

**Comment by greg-1-anderson** [comment]
See [use of native composer features](https://github.com/consolidation/cgr#manual-use-of-native-composer-features) for existing documented workaround. A recommendation to use per-project dependencies could also be placed here. PRs welcome.

This project exists because folks insist on using `composer global require ...` to install things that are not global Composer installers. See [fixing the composer global command](https://pantheon.io/blog/fixing-composer-global-command).  If you never use `composer global`, then you do not need cgr.

**Comment by naderman** [comment]
@greg-1-anderson Thanks, I did read that section which just didn't mention non-global installation so far. I'm basically trying to understand why tools like this are being build rather than trying to encourage people to use regular composer require without the global part. Depending on what the rationale is we may or may not want to incorporate some changes into Composer v2, but I found a link to the issue where this should probably be discussed in your blog post (which also doesn't mention the solution of just not using "global" require at all): https://github.com/composer/composer/issues/5390#issuecomment-224011226 - so I'll read up and comment there instead, sorry for creating an issue here for this!
